package ro.iss.protocol.request;

public enum RequestType {
    LOGIN, LOGOUT, FIND_USER_TYPE,
    FINDALL_BOOKS, FINDALL_READERS, FINDALL_LOANS,
    READERS_BY_NAME, FILTER_LOANS, READER_LOANS,
    ADD_BOOK, DELETE_BOOK, UPDATE_BOOK, MODIFY_BOOKLIST, FILTER_BOOKS,
    ADD_LOAN, DELETE_LOAN, UPDATE_LOAN,
    ADD_READER
}
